# Generated by Django 5.1.3 on 2025-08-19 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_piloto', models.CharField(max_length=10, unique=True, verbose_name='ID del Piloto')),
                ('nombre_completo', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('equipo', models.CharField(max_length=50, verbose_name='Equipo')),
                ('pais', models.CharField(max_length=30, verbose_name='País')),
                ('numero_carro', models.IntegerField(verbose_name='Número del Carro')),
            ],
            options={
                'verbose_name': 'Piloto',
                'verbose_name_plural': 'Pilotos',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sesion', models.CharField(max_length=20, unique=True, verbose_name='ID de la Sesión')),
                ('nombre_sesion', models.CharField(max_length=50, verbose_name='Nombre de la Sesión')),
                ('ubicacion', models.CharField(max_length=100, verbose_name='Ubicación')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha de Fin')),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DatosCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocidad', models.IntegerField(verbose_name='Velocidad (km/h)')),
                ('rpm', models.IntegerField(verbose_name='RPM')),
                ('acelerador', models.FloatField(verbose_name='Acelerador (%)')),
                ('freno', models.BooleanField(verbose_name='Freno Activado')),
                ('timestamp', models.DateTimeField(verbose_name='Marca de Tiempo')),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.piloto', verbose_name='Piloto')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.sesion', verbose_name='Sesión')),
            ],
            options={
                'verbose_name': 'Datos del Carro',
                'verbose_name_plural': 'Datos de los Carros',
                'ordering': ['-timestamp'],
            },
        ),
    ]
