# Generated by Django 5.1.3 on 2025-08-29 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datoscarro',
            options={},
        ),
        migrations.AlterModelOptions(
            name='piloto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sesion',
            options={},
        ),
        migrations.RemoveField(
            model_name='datoscarro',
            name='acelerador',
        ),
        migrations.RemoveField(
            model_name='datoscarro',
            name='freno',
        ),
        migrations.RemoveField(
            model_name='piloto',
            name='id_piloto',
        ),
        migrations.RemoveField(
            model_name='piloto',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='id_sesion',
        ),
        migrations.AlterField(
            model_name='datoscarro',
            name='piloto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.piloto'),
        ),
        migrations.AlterField(
            model_name='datoscarro',
            name='rpm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datoscarro',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.sesion'),
        ),
        migrations.AlterField(
            model_name='datoscarro',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='datoscarro',
            name='velocidad',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='piloto',
            name='equipo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='piloto',
            name='nombre_completo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='piloto',
            name='numero_carro',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='fecha_fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='nombre_sesion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='ubicacion',
            field=models.CharField(max_length=100),
        ),
    ]
