# Generated by Django 5.1.3 on 2025-08-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_alter_datoscarro_options_alter_piloto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piloto',
            options={'ordering': ['-puntos']},
        ),
        migrations.AlterModelOptions(
            name='sesion',
            options={'ordering': ['fecha_inicio']},
        ),
        migrations.AddField(
            model_name='piloto',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='piloto',
            name='pais',
            field=models.CharField(default='No especificado', max_length=50),
        ),
        migrations.AddField(
            model_name='piloto',
            name='podios',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='piloto',
            name='poles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='piloto',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='piloto',
            name='victorias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='piloto',
            name='vueltas_rapidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sesion',
            name='clima',
            field=models.CharField(default='Despejado', max_length=50),
        ),
        migrations.AddField(
            model_name='sesion',
            name='direccion_viento',
            field=models.CharField(default='N', max_length=10),
        ),
        migrations.AddField(
            model_name='sesion',
            name='humedad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sesion',
            name='longitud_circuito',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sesion',
            name='numero_vueltas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sesion',
            name='probabilidad_lluvia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sesion',
            name='temperatura',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='sesion',
            name='tipo_sesion',
            field=models.CharField(default='Práctica', max_length=50),
        ),
        migrations.AddField(
            model_name='sesion',
            name='velocidad_viento',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='DatosCarro',
        ),
    ]
